# 1. Use dim() to set dimension of matrix
x <- 1:15
dim(x) <- c(5, 3)
print(x)

# 2.
a = matrix(0, nrow=4, ncol=4)
print(a)

# 3.cbind is bind by column, rbind is bind by row
b <- rbind(1:8, rev(1:8), rep(3, 8))
print(b)

# 4.
x <- matrix(c(1:16), 4, 4)
y <- matrix(c(17:32), 4, 4)
print(x + y)
print(x - y)
print(x * y)
print(x %*% y)
z <- x / y
print(z)
print(t(z))
print(diag(t(z)))

# 5. One is arrange by row and other one is arrange by column
x <- matrix(x <- 1:9, 3, 3, byrow=TRUE)
print(x)
x <- matrix(x <- 1:9, 3, 3)
print(x)

# 6.
c <- c(1:3)
d <- c(4:6)
print(c %*% d)
print(c %o% d)

# 7. all.equal() compare matrix
e <- matrix(1:6, ncol=2)
f <- matrix(1:6, ncol=2)
print(all.equal(e, f))
print(identical(e, f))
print(e == f)
e <- matrix(1:6, ncol=2)
f <- matrix(2:7, ncol=3)
print(all.equal(e, f))
print(identical(e, f))
print(e == f)

# 8. dim() use to set dimension
g <- 1:9
dim(g) <- c(3, 3)
print(g)

# 9. [] to access list item. $ to access list item by name.
list_data <- list(c("Jan","Feb","Mar"), matrix(c(3,9,5,1,-2,8), nrow = 2), list("green",12.3))
names(list_data) <- c("1st Quarter", "A_Matrix", "A Inner list")
print(list_data[1])
print(list_data[3])
print(list_data$A_Matrix)

# 10.
a = c(5, 7, 2, 9)
ifelse(a %% 2 == 0, "even", "odd")

# 11.
weight <- readline(prompt = "Enter the weight: ")
weight <- as.integer(weight)
height <- readline(prompt = "Enter the height: ")
height <- as.integer(height)
bmi <- round(weight/((height/100)^2), 1)
ifelse(bmi >= 30.0, "Obesity", ifelse(bmi < 30.0 && bmi >= 25.0, "Overweight", ifelse(bmi < 25.0 && bmi >= 18.5, "Normal", "Underweight")))

# 12. list contain different datatype. dataframe use to store data table
y <- list(name="Mike", gender="M", company="ProgramCreek")
y
name <- c("Mike", "Lucy", "John")
age <- c(20, 25, 30)
student <- c(TRUE, FALSE, TRUE) 
df = data.frame(name, age, student)
df

# 13. while determine when to finish loop. repeat execute the code until the stop condition is met.
i <- 0
repeat {if (i==2) break;print(i);i<-i+1}
i <- 0
while (i!=2) {print(i);i<-i+1}